Update main.yml
Signed-off-by: ishurusia5 <ishurusia5@gmail.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,11 +23,16 @@ jobs:
 
     - name: Install AWS CLI
       run: |
-        # Installing the latest version of AWS CLI
-        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-        sudo apt install unzip -y 
-        unzip awscliv2.zip
-        sudo ./aws/install
+        # Check if AWS CLI is already installed
+        if ! command -v aws &> /dev/null; then
+          echo "AWS CLI not found, installing..."
+          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+          unzip awscliv2.zip
+          sudo ./aws/install
+        else
+          echo "AWS CLI already installed, updating..."
+          sudo ./aws/install --update
+        fi
 
     - name: Set up AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
